name: fantasy_creatures
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  form_builder_image_picker: ^4.1.0
  form_builder_validators: ^11.0.0
  get: ^4.6.6
  hive_ce: ^2.6.0
  hive_ce_flutter: ^2.1.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
